# Generated by Django 5.1.1 on 2024-09-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=5000)),
                ('uploadedOn', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=500)),
            ],
        ),
    ]
