# Generated by Django 5.1.1 on 2024-09-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='banner',
            field=models.ImageField(default='default', upload_to='Media'),
            preserve_default=False,
        ),
    ]
