# Generated by Django 5.1.1 on 2024-09-14 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_slider_sliderimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='sliderImage',
            new_name='banner',
        ),
    ]
