# Generated by Django 5.1.1 on 2024-09-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_sliderimage_slider_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default='1000', max_length=5000),
            preserve_default=False,
        ),
    ]
